"use strict";

const { test } = require("node:test");
const assert = require("node:assert/strict");

const { renderGo2rtcConfig } = require("../dist/streaming/go2rtcManager");

test("generated go2rtc config: localhost-only listeners, both tiers per camera", () => {
  const yaml = renderGo2rtcConfig({
    apiPort: 1984,
    rtspPort: 8554,
    cameras: [
      {
        id: "home",
        mainUrl: "rtsp://user:pass@192.168.0.208:554/stream1",
        subUrl: "rtsp://user:pass@192.168.0.208:554/stream2",
      },
    ],
  });

  assert.equal(
    yaml,
    [
      "# generated by homebridge-tapo-camera-ng — do not edit",
      "api:",
      '  listen: "127.0.0.1:1984"',
      "rtsp:",
      '  listen: "127.0.0.1:8554"',
      "webrtc:",
      '  listen: ""',
      "rtmp:",
      '  listen: ""',
      "srtp:",
      '  listen: ""',
      "log:",
      "  level: warn",
      "streams:",
      '  home_main: "rtsp://user:pass@192.168.0.208:554/stream1"',
      '  home_sub: "rtsp://user:pass@192.168.0.208:554/stream2"',
      "",
    ].join("\n")
  );
});
