import { ChildProcess, spawn } from "child_process";
import { createServer } from "net";
import { existsSync } from "fs";
import { mkdir, writeFile } from "fs/promises";
import path from "path";
import { Logging } from "homebridge";
import {
  CameraSourceConfig,
  SourceProvider,
  StreamTier,
} from "./sourceProvider";

const RESTART_BACKOFF_MAX_MS = 30_000;
const RESTART_BACKOFF_RESET_MS = 60_000;
const HEALTH_POLL_MS = 30_000;
const STARTUP_TIMEOUT_MS = 15_000;

export type Go2rtcManagerOptions = {
  /** Directory for the generated config file (created if missing). */
  workDir: string;
  /** Explicit binary path (config override). */
  binaryPath?: string;
};

/** Single-quoted YAML scalar (handles spaces, colons, quotes in URLs/commands). */
function yamlScalar(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

/** Pure so tests can lock the generated config exactly. */
export function renderGo2rtcConfig(opts: {
  apiPort: number;
  rtspPort: number;
  cameras: CameraSourceConfig[];
}): string {
  const lines = [
    "# generated by homebridge-tapo-camera-ng — do not edit",
    "api:",
    `  listen: "127.0.0.1:${opts.apiPort}"`,
    "rtsp:",
    `  listen: "127.0.0.1:${opts.rtspPort}"`,
    // Everything below binds nothing: localhost-only surface.
    "webrtc:",
    '  listen: ""',
    "rtmp:",
    '  listen: ""',
    "srtp:",
    '  listen: ""',
    "log:",
    "  level: warn",
    "streams:",
  ];
  for (const cam of opts.cameras) {
    if (cam.kind === "rtsp") {
      lines.push(`  ${cam.id}_main: ${yamlScalar(cam.mainUrl)}`);
      lines.push(`  ${cam.id}_sub: ${yamlScalar(cam.subUrl)}`);
    } else {
      lines.push(`  ${cam.id}: ${yamlScalar(cam.command)}`);
    }
  }
  return lines.join("\n") + "\n";
}

async function pickFreePort(): Promise<number> {
  return new Promise((resolve, reject) => {
    const server = createServer();
    server.once("error", reject);
    server.listen(0, "127.0.0.1", () => {
      const address = server.address();
      if (address === null || typeof address === "string") {
        server.close();
        reject(new Error("Could not allocate a port"));
        return;
      }
      const port = address.port;
      server.close(() => resolve(port));
    });
  });
}

export class Go2rtcManager implements SourceProvider {
  private readonly cameras: CameraSourceConfig[] = [];
  private child: ChildProcess | null = null;
  private apiPort = 0;
  private rtspPort = 0;
  private ready = false;
  private stopped = false;
  private restarts = 0;
  private restartTimer: NodeJS.Timeout | null = null;
  private healthTimer: NodeJS.Timeout | null = null;
  private configPath = "";

  constructor(
    private readonly log: Logging,
    private readonly opts: Go2rtcManagerOptions
  ) {}

  private readonly kinds = new Map<string, "rtsp" | "exec">();
  private readonly execIds: string[] = [];
  private keepaliveAbort: AbortController | null = null;

  registerCamera(config: CameraSourceConfig): void {
    if (!/^[A-Za-z0-9-]+$/.test(config.id)) {
      throw new Error(`Invalid camera id "${config.id}"`);
    }
    this.cameras.push(config);
    this.kinds.set(config.id, config.kind);
    if (config.kind === "exec") this.execIds.push(config.id);
  }

  // exec sources (HTML cameras) cold-start their capture only when first
  // consumed — several seconds — which blows past HomeKit's ~4s stream-start
  // patience and, worse, stalls a mosaic's xstack (it waits for every input).
  // Hold a cheap persistent consumer on each so go2rtc keeps them hot; the
  // mosaic and standalone HTML cameras then open instantly. Discards the
  // stream body, so the only real cost is the (low-motion) capture encode.
  private startKeepalive(): void {
    if (this.execIds.length === 0) return;
    this.keepaliveAbort = new AbortController();
    this.log.info(`Keeping ${this.execIds.length} HTML source(s) warm`);
    for (const id of this.execIds) void this.keepWarm(id);
  }

  private async keepWarm(id: string): Promise<void> {
    while (!this.stopped) {
      try {
        const res = await fetch(
          `http://127.0.0.1:${this.apiPort}/api/stream.mp4?src=${id}`,
          { signal: this.keepaliveAbort?.signal }
        );
        const reader = res.body?.getReader();
        if (!reader) throw new Error("no stream body");
        for (;;) {
          const { done } = await reader.read();
          if (done) break;
        }
      } catch (err) {
        if (this.stopped || (err as Error).name === "AbortError") return;
        this.log.debug(`keepalive ${id} reconnecting: ${(err as Error).message}`);
      }
      await new Promise((r) => setTimeout(r, 2000));
    }
  }

  private resolveBinary(): string {
    const candidates = [
      this.opts.binaryPath,
      process.env.GO2RTC_PATH,
      path.join(__dirname, "..", "..", "bin", "go2rtc"),
    ].filter((p): p is string => Boolean(p));
    for (const candidate of candidates) {
      if (existsSync(candidate)) return candidate;
    }
    throw new Error(
      "go2rtc binary not found. The postinstall download may have failed — " +
        "re-run `node scripts/download-go2rtc.mjs` in the plugin directory, " +
        "or set go2rtcPath in the platform config."
    );
  }

  async start(): Promise<void> {
    if (this.cameras.length === 0) {
      throw new Error("No cameras registered before start()");
    }
    const binary = this.resolveBinary();
    this.apiPort = await pickFreePort();
    this.rtspPort = await pickFreePort();

    await mkdir(this.opts.workDir, { recursive: true });
    this.configPath = path.join(this.opts.workDir, "go2rtc.yaml");
    await writeFile(
      this.configPath,
      renderGo2rtcConfig({
        apiPort: this.apiPort,
        rtspPort: this.rtspPort,
        cameras: this.cameras,
      }),
      "utf8"
    );

    this.spawnChild(binary);
    await this.waitForHealthy();
    this.log.info(
      `go2rtc ready (api :${this.apiPort}, rtsp :${this.rtspPort}, ${this.cameras.length} camera(s))`
    );

    this.healthTimer = setInterval(() => {
      void this.healthCheck();
    }, HEALTH_POLL_MS);
    this.healthTimer.unref();

    this.startKeepalive();
  }

  private spawnChild(binary: string): void {
    if (this.stopped) return;

    const child = spawn(binary, ["-config", this.configPath], {
      stdio: ["ignore", "pipe", "pipe"],
    });
    this.child = child;
    this.ready = false;

    setTimeout(() => {
      if (this.child === child) this.restarts = 0;
    }, RESTART_BACKOFF_RESET_MS).unref();

    // Always drain — an unread pipe eventually blocks the child.
    child.stdout?.on("data", (d: Buffer) =>
      this.log.debug(`go2rtc: ${d.toString().trim()}`)
    );
    child.stderr?.on("data", (d: Buffer) =>
      this.log.debug(`go2rtc: ${d.toString().trim()}`)
    );
    child.on("error", (err) => {
      this.log.error(`Failed to start go2rtc (${err.message})`);
    });
    child.on("exit", (code, signal) => {
      if (this.stopped || this.child !== child) return;
      this.ready = false;
      this.log.warn(
        `go2rtc exited unexpectedly (${code ?? signal}), restarting`
      );
      this.scheduleRestart(binary);
    });
  }

  private scheduleRestart(binary: string): void {
    if (this.stopped || this.restartTimer) return;
    const delay = Math.min(RESTART_BACKOFF_MAX_MS, 1000 * 2 ** this.restarts);
    this.restarts++;
    this.log.info(`Restarting go2rtc in ${delay / 1000}s`);
    this.restartTimer = setTimeout(() => {
      this.restartTimer = null;
      this.spawnChild(binary);
      void this.waitForHealthy().catch((err) =>
        this.log.warn(`go2rtc not healthy after restart: ${err.message}`)
      );
    }, delay);
  }

  private async healthCheck(): Promise<void> {
    if (this.stopped || !this.child) return;
    try {
      const res = await fetch(`http://127.0.0.1:${this.apiPort}/api`, {
        signal: AbortSignal.timeout(5000),
      });
      this.ready = res.ok;
    } catch {
      this.ready = false;
      this.log.warn("go2rtc health check failed, killing for restart");
      try {
        this.child.kill("SIGKILL");
      } catch {
        /* already gone */
      }
    }
  }

  private async waitForHealthy(): Promise<void> {
    const deadline = Date.now() + STARTUP_TIMEOUT_MS;
    while (Date.now() < deadline) {
      try {
        const res = await fetch(`http://127.0.0.1:${this.apiPort}/api`, {
          signal: AbortSignal.timeout(2000),
        });
        if (res.ok) {
          this.ready = true;
          return;
        }
      } catch {
        /* not up yet */
      }
      await new Promise((r) => setTimeout(r, 250));
    }
    throw new Error("go2rtc did not become healthy in time");
  }

  isReady(): boolean {
    return this.ready;
  }

  /** Relay stream name: rtsp cameras are per-tier, exec cameras single. */
  private streamName(cameraId: string, tier: StreamTier): string {
    return this.kinds.get(cameraId) === "exec"
      ? cameraId
      : `${cameraId}_${tier}`;
  }

  getSourceUrl(cameraId: string, tier: StreamTier): string {
    if (this.rtspPort === 0) throw new Error("go2rtc not started");
    return `rtsp://127.0.0.1:${this.rtspPort}/${this.streamName(cameraId, tier)}`;
  }

  async getFrame(cameraId: string): Promise<Buffer> {
    const res = await fetch(
      `http://127.0.0.1:${this.apiPort}/api/frame.jpeg?src=${this.streamName(cameraId, "sub")}`,
      { signal: AbortSignal.timeout(8000) }
    );
    if (!res.ok) throw new Error(`frame.jpeg returned ${res.status}`);
    return Buffer.from(await res.arrayBuffer());
  }

  stop(): void {
    this.stopped = true;
    this.ready = false;
    try {
      this.keepaliveAbort?.abort();
    } catch {
      /* nothing bound */
    }
    if (this.restartTimer) {
      clearTimeout(this.restartTimer);
      this.restartTimer = null;
    }
    if (this.healthTimer) {
      clearInterval(this.healthTimer);
      this.healthTimer = null;
    }
    try {
      this.child?.kill("SIGTERM");
    } catch {
      /* already gone */
    }
    this.child = null;
  }
}
